apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zxcvzxcbv
spec:
  project: default
  source:
    repoURL: ''
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
